namespace SvelteNet.AspNetCore.Dev;

using SvelteNet.TypeGen;
using System.Reflection;

/// <summary>
/// Dev-time code generation: TypeScript types for every [SvelteProp] model, a typed
/// data interface + scaffold component per SveltePage, the mount/render runtime helpers,
/// and Vite config. Generated .types.ts files are overwritten each run; everything else
/// is written only when missing.
/// </summary>
public static class SvelteScaffolder
{
	public static void Run(SvelteOptions options, IReadOnlyList<Type>? pageTypes = null, IReadOnlyList<Type>? componentModelTypes = null, IReadOnlyList<Type>? remoteServiceTypes = null)
	{
		var svelteDir = Path.Combine(options.ContentRoot, options.PagesPath);
		Directory.CreateDirectory(svelteDir);

		var pages = pageTypes?.ToList() ?? TypeDiscovery.FindTypes(t => t.IsSubclassOf(typeof(SveltePage)) && !t.IsAbstract);
		var componentModels = componentModelTypes?.ToList() ?? TypeDiscovery.FindTypes(t => t.IsDefined(typeof(SvelteComponentAttribute), false));
		var remoteServices = remoteServiceTypes?.ToList() ?? TypeDiscovery.FindTypes(t => t.IsDefined(typeof(SvelteRemoteAttribute), false));

		WriteSharedTypes(svelteDir, pages, componentModels, remoteServices);
		foreach (var page in pages) ScaffoldPage(svelteDir, page);
		foreach (var model in componentModels) ScaffoldComponentModel(svelteDir, model);
		WriteRemoteClient(svelteDir, remoteServices);

		WriteIfMissing(Path.Combine(svelteDir, "mount.ts"), SvelteTemplates.MountTs);
		WriteIfMissing(Path.Combine(svelteDir, "render.ts"), SvelteTemplates.RenderTs);
		WriteIfMissing(Path.Combine(options.ContentRoot, "vite.config.ts"), SvelteTemplates.ViteConfig(options));
		WriteIfMissing(Path.Combine(options.ContentRoot, "package.json"), SvelteTemplates.PackageJson);
		WriteRouteIds(options, svelteDir);
	}

	private static PropertyInfo[] SvelteProps(Type type) => type
		.GetProperties()
		.Where(p => p.IsDefined(typeof(SveltePropAttribute), true))
		.ToArray();

	private static void WriteSharedTypes(string svelteDir, List<Type> pages, List<Type> componentModels, List<Type> remoteServices)
	{
		var remoteTypes = remoteServices
			.Select(SvelteNet.Remote.SvelteRemoteDescriptors.For)
			.SelectMany(d => d.Methods)
			.SelectMany(m => m.Parameters.Select(p => p.Type).Append(m.ReturnType))
			.Where(t => t != typeof(void) && t != typeof(CancellationToken));

		var rootTypes = pages.SelectMany(SvelteProps)
			.Select(p => p.PropertyType)
			.Concat(componentModels)
			.Concat(remoteTypes)
			.Distinct()
			.ToList();

		// Emit open generic definitions once, however many closed forms are referenced.
		var interfaces = rootTypes.GetAllTypes()
			.Select(t => t.IsGenericType ? t.GetGenericTypeDefinition() : t)
			.Distinct()
			.Select(t => t.GetTypescriptInterface(false));

		File.WriteAllText(Path.Combine(svelteDir, "types.ts"), $"""
/* eslint-disable */
// Generated by SvelteNet — do not edit.

{string.Join(Environment.NewLine + Environment.NewLine, interfaces)}
""");
	}

	private static void ScaffoldPage(string svelteDir, Type page)
	{
		var name = PageName(page);
		var dir = Path.Combine(svelteDir, PageDirectory(page));
		Directory.CreateDirectory(dir);

		var props = SvelteProps(page);
		var fields = props
			.Select(p => $"\t{p.Name.ToCamelCase()}: {p.PropertyType.TsType()};")
			.Append("\tmodelState: Record<string, string[]>;")
			.Append("\tantiforgeryToken: string;");

		var imports = new SortedSet<string>(StringComparer.Ordinal);
		foreach (var p in props) CollectImports(p.PropertyType, imports);

		var relImport = Path.GetRelativePath(dir, Path.Combine(svelteDir, "types")).Replace('\\', '/');
		if (!relImport.StartsWith('.')) relImport = "./" + relImport;
		var importLine = imports.Count == 0
			? string.Empty
			: $"import type {{ {string.Join(", ", imports)} }} from '{relImport}';{Environment.NewLine}";

		File.WriteAllText(Path.Combine(dir, $"{name}.types.ts"), $$"""
// Generated by SvelteNet — do not edit.
{{importLine}}
export interface {{name}}Data {
{{string.Join(Environment.NewLine, fields)}}
}
""");

		WriteIfMissing(Path.Combine(dir, $"{name}.svelte"), SvelteTemplates.Page(name));
	}

	/// <summary>
	/// Scaffolds the component for a [SvelteComponent] model. Its data interface is
	/// the model type itself, which WriteSharedTypes already emitted into types.ts.
	/// </summary>
	private static void ScaffoldComponentModel(string svelteDir, Type model)
	{
		var component = SvelteComponentResolver.Resolve(model);
		var path = Path.Combine(svelteDir, component + ".svelte");
		Directory.CreateDirectory(Path.GetDirectoryName(path)!);

		var depth = component.Count(c => c == '/');
		var typesImport = depth == 0 ? "./types" : string.Concat(Enumerable.Repeat("../", depth)) + "types";

		WriteIfMissing(path, SvelteTemplates.ComponentModelPage(model.TsType(), typesImport));
	}

	/// <summary>
	/// Generates the typed remote-function client, mirroring SvelteKit's remote
	/// functions: one flat export per [Query]/[Command]/[Form] method. Regenerated
	/// every run.
	/// </summary>
	private static void WriteRemoteClient(string svelteDir, List<Type> remoteServices)
	{
		if (remoteServices.Count == 0) return;

		var imports = new SortedSet<string>(StringComparer.Ordinal);
		var usedKinds = new SortedSet<string>(StringComparer.Ordinal);
		var exports = new List<string>();

		var methods = remoteServices
			.Select(SvelteNet.Remote.SvelteRemoteDescriptors.For)
			.SelectMany(d => d.Methods.Select(m => (Service: d.Name, Method: m)))
			.OrderBy(x => x.Method.Name, StringComparer.Ordinal);

		foreach (var (service, method) in methods)
		{
			foreach (var p in method.Parameters) CollectImports(p.Type, imports);
			if (method.ReturnType != typeof(void)) CollectImports(method.ReturnType, imports);

			var tsReturn = method.ReturnType == typeof(void) ? "void" : method.ReturnType.TsType();
			var name = method.Name.ToCamelCase();
			var path = $"{service}/{method.Name}";

			exports.Add(method.Kind switch
			{
				RemoteKind.Form => FormExport(name, path, tsReturn, method.Parameters),
				_ => CallableExport(method.Kind == RemoteKind.Query ? "query" : "command", name, path, tsReturn, method.Parameters)
			});
			usedKinds.Add(method.Kind switch
			{
				RemoteKind.Query => "query",
				RemoteKind.Command => "command",
				_ => "form"
			});
		}

		var importLine = imports.Count == 0
			? string.Empty
			: $"import type {{ {string.Join(", ", imports)} }} from './types';{Environment.NewLine}";

		File.WriteAllText(Path.Combine(svelteDir, "remote.ts"), $$"""
/* eslint-disable */
// Generated by SvelteNet — do not edit.
import { {{string.Join(", ", usedKinds)}} } from 'sveltenet/remote';
{{importLine}}
{{string.Join(Environment.NewLine, exports)}}
""");
	}

	private static string CallableExport(string kind, string name, string path, string tsReturn, SvelteNet.Remote.RemoteParameter[] parameters)
	{
		if (parameters.Length == 0)
			return $"export const {name} = {kind}<{tsReturn}>('{path}');";

		var tuple = string.Join(", ", parameters.Select(p => $"{p.Name}: {p.Type.TsType()}"));
		var names = string.Join(", ", parameters.Select(p => p.Name));
		return $"export const {name} = {kind}<{tsReturn}, [{tuple}]>('{path}', ({names}) => ({{ {names} }}));";
	}

	private static string FormExport(string name, string path, string tsReturn, SvelteNet.Remote.RemoteParameter[] parameters)
	{
		var fields = string.Join("; ", parameters.Select(p => $"{p.Name}: {p.Type.TsType()}"));
		var fieldsType = parameters.Length == 0 ? "{}" : $"{{ {fields} }}";
		return $"export const {name} = form<{tsReturn}, {fieldsType}>('{path}');";
	}

	/// <summary>Collects the named types a page's data interface must import from the shared types file.</summary>
	private static void CollectImports(Type? type, ISet<string> names)
	{
		if (type is null) return;
		type = Nullable.GetUnderlyingType(type) ?? type;
		if (type.IsGenericParameter || type.IsSimpleType()) return;

		if (type.IsDictionaryType())
		{
			foreach (var arg in type.GetGenericArguments()) CollectImports(arg, names);
			return;
		}

		if (type.IsCollectionType())
		{
			CollectImports(type.GetCollectionType(), names);
			return;
		}

		if (type.IsGenericType)
		{
			foreach (var arg in type.GetGenericArguments()) CollectImports(arg, names);
			names.Add(type.Name.RemoveTypeArity());
			return;
		}

		if (type.IsSystemType()) return;
		names.Add(type.Name);
	}

	private static string PageName(Type page)
	{
		var name = page.Name;
		return name.Length > "Model".Length && name.EndsWith("Model", StringComparison.Ordinal)
			? name[..^"Model".Length]
			: name;
	}

	/// <summary>Mirrors the Razor Pages folder structure, derived from the "*.Pages.*" namespace convention.</summary>
	private static string PageDirectory(Type page)
	{
		var ns = page.Namespace ?? string.Empty;
		var index = ns.IndexOf(".Pages", StringComparison.Ordinal);
		if (index < 0) return string.Empty;
		return ns[(index + ".Pages".Length)..].TrimStart('.').Replace('.', '/');
	}

	/// <summary>Generates a global RouteId union of all page routes, for typed hrefs.</summary>
	private static void WriteRouteIds(SvelteOptions options, string svelteDir)
	{
		var pagesDir = Path.Combine(options.ContentRoot, "Pages");
		if (!Directory.Exists(pagesDir)) return;

		var routes = Directory.GetFiles(pagesDir, "*.cshtml", SearchOption.AllDirectories)
			.Select(f => "/" + Path.GetRelativePath(pagesDir, f).Replace('\\', '/'))
			.Where(f => !f.Contains("/_"))
			.Select(f => f[..^".cshtml".Length])
			.Select(f => f == "/Index" ? "/" : f.EndsWith("/Index", StringComparison.Ordinal) ? f[..^"/Index".Length] : f)
			.Distinct()
			.Order()
			.Select(f => $"\"{f}\"")
			.ToList();

		if (routes.Count == 0) return;

		File.WriteAllText(Path.Combine(svelteDir, "routes.d.ts"), $$"""
// Generated by SvelteNet — do not edit.
declare global {
	type RouteId = {{string.Join(" | ", routes)}} | (string & {});
}
export {};
""");
	}

	private static void WriteIfMissing(string path, string content)
	{
		if (File.Exists(path)) return;
		File.WriteAllText(path, content);
		Console.WriteLine($"[SvelteNet] Scaffolded {path}");
	}
}
