/* eslint-disable */
// Generated by SvelteNet — do not edit.
import { command, form, query } from 'sveltenet/remote';

export class TodoApi {
	static readonly CreateTodo = form<Todo, { label: string; priority: Priority }>('TodoApi/CreateTodo');
	static readonly GetStats = query<TodoStats>('TodoApi/GetStats');
	static readonly GetTodos = query<Todo[]>('TodoApi/GetTodos');
	static readonly SubmitFeedback = command<string, [feedback: Feedback]>('TodoApi/SubmitFeedback', (feedback) => ({ feedback }));
	static readonly Subscribe = form<string, { email: string }>('TodoApi/Subscribe');
	static readonly ToggleTodo = command<void, [id: number]>('TodoApi/ToggleTodo', (id) => ({ id }));
}
