namespace SvelteNet.Generators;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

/// <summary>
/// Emits the application metadata used by page rendering and TypeScript generation:
/// strongly typed page-prop getters, component mappings, and serializer-aware model
/// declarations. Runtime code consumes this registry without scanning assemblies.
/// </summary>
[Generator]
public sealed class SvelteMetadataGenerator : IIncrementalGenerator
{
	private sealed record PageModel(
		string FullType,
		string Component,
		PropertyModel[] Properties);

	private sealed record ComponentModel(string FullType, string Component);

	private sealed record PropertyModel(
		string ClrName,
		string JsonName,
		string FullType,
		string TypeScriptType,
		bool IsNullable,
		string[] Imports);

	private sealed record TypeModel(string TypeOf, string TypeScriptName, string Declaration);

	private static readonly SymbolDisplayFormat FullTypeFormat =
		SymbolDisplayFormat.FullyQualifiedFormat.WithMiscellaneousOptions(
			SymbolDisplayMiscellaneousOptions.IncludeNullableReferenceTypeModifier |
			SymbolDisplayMiscellaneousOptions.UseSpecialTypes |
			SymbolDisplayMiscellaneousOptions.EscapeKeywordIdentifiers);

	public void Initialize(IncrementalGeneratorInitializationContext context)
	{
		var types = context.SyntaxProvider.CreateSyntaxProvider(
				static (node, _) => node is TypeDeclarationSyntax,
				static (ctx, _) => ctx.SemanticModel.GetDeclaredSymbol((TypeDeclarationSyntax)ctx.Node) as INamedTypeSymbol)
			.Where(static symbol => symbol is not null);

		context.RegisterSourceOutput(types.Collect(), static (spc, symbols) =>
		{
			var distinct = symbols
				.Where(s => s is not null)
				.Cast<INamedTypeSymbol>()
				.GroupBy(s => s, SymbolEqualityComparer.Default)
				.Select(g => g.First())
				.ToArray();
			var source = Emit(distinct);
			if (source is not null) spc.AddSource("SvelteNet.Metadata.g.cs", source);
		});
	}

	private static string? Emit(IReadOnlyList<INamedTypeSymbol> sourceTypes)
	{
		var pages = new List<PageModel>();
		var components = new List<ComponentModel>();
		var remoteInitializers = new List<string>();
		var roots = new HashSet<ITypeSymbol>(SymbolEqualityComparer.Default);

		foreach (var type in sourceTypes)
		{
			if (!CanReference(type)) continue;

			if (IsPage(type))
			{
				var properties = PageProperties(type).Select(Property).ToArray();
				pages.Add(new PageModel(FullType(type), PageComponent(type), properties));
				foreach (var property in PageProperties(type)) roots.Add(property.Type);
			}

			var componentAttribute = Attribute(type, "SvelteNet.SvelteComponentAttribute");
			if (componentAttribute is not null)
			{
				var component = componentAttribute.ConstructorArguments.Length > 0
					? componentAttribute.ConstructorArguments[0].Value as string
					: null;
				components.Add(new ComponentModel(FullType(type), component ?? $"Components/{TrimModelSuffix(type.Name)}"));
				roots.Add(type);
			}

			if (Attribute(type, "SvelteNet.SvelteRemoteAttribute") is not null)
			{
				var remoteMethods = type.GetMembers().OfType<IMethodSymbol>().Where(IsRemoteMethod).ToArray();
				if (!remoteMethods.GroupBy(m => m.Name, StringComparer.OrdinalIgnoreCase).Any(g => g.Count() > 1))
				{
					var fullName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
					remoteInitializers.Add($"{type.Name}RemoteDispatcher_{StableHash(fullName):x8}.Init();");
				}
				foreach (var method in remoteMethods)
				{
					foreach (var parameter in method.Parameters.Where(p => !IsCancellationToken(p.Type)))
						roots.Add(parameter.Type);
					roots.Add(UnwrapReturn(method.ReturnType));
				}
			}
		}

		var modelTypes = new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default);
		foreach (var root in roots) CollectModelTypes(root, modelTypes);
		var types = modelTypes
			.OrderBy(t => t.ToDisplayString(), StringComparer.Ordinal)
			.Select(CreateTypeModel)
			.ToArray();

		if (pages.Count == 0 && components.Count == 0 && types.Length == 0) return null;

		var sb = new StringBuilder();
		sb.AppendLine("// <auto-generated by SvelteNet.Generators />");
		sb.AppendLine("#nullable enable");
		sb.AppendLine("namespace SvelteNet.Generated");
		sb.AppendLine("{");
		sb.AppendLine("\tinternal static class __SvelteNetMetadata");
		sb.AppendLine("\t{");
		sb.AppendLine("\t\t[global::System.Runtime.CompilerServices.ModuleInitializer]");
		sb.AppendLine("\t\tinternal static void Init()");
		sb.AppendLine("\t\t{");
		foreach (var initializer in remoteInitializers.OrderBy(x => x, StringComparer.Ordinal))
			sb.AppendLine($"\t\t\t{initializer}");
		sb.AppendLine("\t\t\tvar owner = typeof(__SvelteNetMetadata).Assembly;");

		foreach (var page in pages.OrderBy(p => p.FullType, StringComparer.Ordinal))
		{
			sb.AppendLine("\t\t\tglobal::SvelteNet.Generated.SvelteGeneratedMetadata.RegisterPage(");
			sb.AppendLine("\t\t\t\tnew global::SvelteNet.Generated.SvelteGeneratedPage(");
			sb.AppendLine($"\t\t\t\t\towner, typeof({page.FullType}), {Literal(page.Component)},");
			sb.AppendLine("\t\t\t\t\tnew global::SvelteNet.Generated.SvelteGeneratedProperty[]");
			sb.AppendLine("\t\t\t\t\t{");
			foreach (var property in page.Properties)
			{
				var imports = string.Join(", ", property.Imports.Select(Literal));
				sb.AppendLine("\t\t\t\t\t\tnew global::SvelteNet.Generated.SvelteGeneratedProperty(");
				sb.AppendLine($"\t\t\t\t\t\t\t{Literal(property.ClrName)}, {Literal(property.JsonName)}, typeof({property.FullType}),");
				sb.AppendLine($"\t\t\t\t\t\t\t{Literal(property.TypeScriptType)}, {(property.IsNullable ? "true" : "false")},");
				sb.AppendLine($"\t\t\t\t\t\t\tnew string[] {{ {imports} }},");
				sb.AppendLine($"\t\t\t\t\t\t\tstatic instance => (({page.FullType})instance).{EscapeIdentifier(property.ClrName)}),");
			}
			sb.AppendLine("\t\t\t\t\t}));");
		}

		foreach (var component in components.OrderBy(c => c.FullType, StringComparer.Ordinal))
		{
			sb.AppendLine("\t\t\tglobal::SvelteNet.Generated.SvelteGeneratedMetadata.RegisterComponent(");
			sb.AppendLine($"\t\t\t\tnew global::SvelteNet.Generated.SvelteGeneratedComponent(owner, typeof({component.FullType}), {Literal(component.Component)}));");
		}

		foreach (var type in types)
		{
			sb.AppendLine("\t\t\tglobal::SvelteNet.Generated.SvelteGeneratedMetadata.RegisterType(");
			sb.AppendLine($"\t\t\t\tnew global::SvelteNet.Generated.SvelteGeneratedType(owner, typeof({type.TypeOf}), {Literal(type.TypeScriptName)}, {Literal(type.Declaration)}));");
		}

		sb.AppendLine("\t\t}");
		sb.AppendLine("\t}");
		sb.AppendLine("}");
		return sb.ToString();
	}

	private static PropertyModel Property(IPropertySymbol property)
	{
		var nullable = IsNullable(property.Type, property.NullableAnnotation);
		var imports = new HashSet<string>(StringComparer.Ordinal);
		CollectImports(property.Type, imports);
		return new PropertyModel(
			property.Name,
			JsonName(property),
			FullType(property.Type),
			TypeScriptType(property.Type, includeNull: nullable),
			nullable,
			imports.OrderBy(x => x, StringComparer.Ordinal).ToArray());
	}

	private static TypeModel CreateTypeModel(INamedTypeSymbol type)
	{
		var definition = type.OriginalDefinition;
		var typeName = TypeScriptName(definition);
		var typeOf = TypeOf(definition);

		if (definition.TypeKind == TypeKind.Enum)
		{
			var members = definition.GetMembers().OfType<IFieldSymbol>()
				.Where(f => f.HasConstantValue)
				.Select(f =>
				{
					var attribute = Attribute(f, "System.Text.Json.Serialization.JsonStringEnumMemberNameAttribute");
					var name = attribute?.ConstructorArguments.FirstOrDefault().Value as string ?? CamelCase(f.Name);
					return $"'{EscapeTypeScriptString(name)}'";
				});
			return new TypeModel(typeOf, typeName, $"export type {typeName} = {string.Join(" | ", members)};");
		}

		var lines = SerializableProperties(definition).Select(p =>
		{
			var nullable = IsNullable(p.Type, p.NullableAnnotation);
			var optional = IsConditionallyIgnored(p);
			var typeScriptType = HasJsonConverter(p) ? "unknown" : TypeScriptType(p.Type, includeNull: nullable);
			return $"\t{TypeScriptPropertyName(JsonName(p))}{(optional ? "?" : "")}: {typeScriptType};";
		});
		var declaration = $"export interface {typeName} {{\n{string.Join("\n", lines)}\n}}";
		return new TypeModel(typeOf, typeName, declaration);
	}

	private static void CollectModelTypes(ITypeSymbol type, HashSet<INamedTypeSymbol> result)
	{
		type = StripNullable(type);
		if (type is IArrayTypeSymbol array)
		{
			if (array.ElementType.SpecialType != SpecialType.System_Byte) CollectModelTypes(array.ElementType, result);
			return;
		}

		if (type is not INamedTypeSymbol named) return;
		foreach (var argument in named.TypeArguments) CollectModelTypes(argument, result);
		if (named.TypeKind == TypeKind.Enum)
		{
			result.Add(named.OriginalDefinition);
			return;
		}
		if (IsSimple(named) || IsCollection(named) || IsDictionary(named) || named.SpecialType != SpecialType.None) return;

		var definition = named.OriginalDefinition;
		if (!result.Add(definition)) return;
		if (definition.TypeKind == TypeKind.Enum || HasJsonConverter(definition)) return;
		foreach (var property in SerializableProperties(definition)) CollectModelTypes(property.Type, result);
	}

	private static IEnumerable<IPropertySymbol> SerializableProperties(INamedTypeSymbol type)
	{
		var seen = new HashSet<string>(StringComparer.Ordinal);
		for (var current = type; current is not null; current = current.BaseType)
		{
			foreach (var property in current.GetMembers().OfType<IPropertySymbol>())
			{
				if (property.IsStatic || property.IsIndexer || property.GetMethod?.DeclaredAccessibility != Accessibility.Public)
					continue;
				if (IsIgnored(property) || !seen.Add(property.Name)) continue;
				yield return property;
			}
		}
	}

	private static IEnumerable<IPropertySymbol> PageProperties(INamedTypeSymbol type) =>
		SerializableProperties(type).Where(p => Attribute(p, "SvelteNet.SveltePropAttribute") is not null);

	private static bool IsPage(INamedTypeSymbol type)
	{
		for (var current = type.BaseType; current is not null; current = current.BaseType)
		{
			if (current.ToDisplayString() == "SvelteNet.AspNetCore.SveltePage") return !type.IsAbstract;
		}

		return false;
	}

	private static bool CanReference(INamedTypeSymbol type)
	{
		for (var current = type; current is not null; current = current.ContainingType)
		{
			if (current.DeclaredAccessibility is Accessibility.Private or Accessibility.Protected)
				return false;
		}
		return true;
	}

	private static bool IsRemoteMethod(IMethodSymbol method) =>
		method.MethodKind == MethodKind.Ordinary &&
		method.DeclaredAccessibility == Accessibility.Public &&
		!method.IsStatic &&
		(method.GetAttributes().Any(a => a.AttributeClass?.ToDisplayString() is
			"SvelteNet.QueryAttribute" or "SvelteNet.CommandAttribute" or "SvelteNet.FormAttribute"));

	private static ITypeSymbol UnwrapReturn(ITypeSymbol type)
	{
		if (type is INamedTypeSymbol { IsGenericType: true, TypeArguments.Length: 1 } named &&
			named.ConstructedFrom.ToDisplayString() is "System.Threading.Tasks.Task<TResult>" or "System.Threading.Tasks.ValueTask<TResult>")
			return named.TypeArguments[0];
		return type;
	}

	internal static string TypeScriptType(ITypeSymbol type, bool includeNull)
	{
		type = StripNullable(type);
		string result;

		if (type is IArrayTypeSymbol array)
			result = array.ElementType.SpecialType == SpecialType.System_Byte
				? "string"
				: $"{TypeScriptType(array.ElementType, includeNull: IsNullable(array.ElementType, array.ElementNullableAnnotation))}[]";
		else if (type is ITypeParameterSymbol parameter)
			result = parameter.Name;
		else if (type is not INamedTypeSymbol named)
			result = "unknown";
		else if (HasJsonConverter(named))
			result = "unknown";
		else if (SimpleType(named) is { } simple)
			result = simple;
		else if (TryDictionary(named, out var key, out var value))
			result = $"{{ [key: {DictionaryKeyType(key)}]: {TypeScriptType(value, IsNullable(value, value.NullableAnnotation))}; }}";
		else if (TryCollection(named, out var element))
			result = $"{TypeScriptType(element, IsNullable(element, element.NullableAnnotation))}[]";
		else if (named.IsGenericType)
			result = $"{named.Name}<{string.Join(", ", named.TypeArguments.Select(a => TypeScriptType(a, IsNullable(a, a.NullableAnnotation))))}>";
		else
			result = named.Name;

		return includeNull && result != "null" ? $"{result} | null" : result;
	}

	private static string? SimpleType(INamedTypeSymbol type) =>
		type.SpecialType switch
		{
			SpecialType.System_String or SpecialType.System_Char => "string",
			SpecialType.System_Boolean => "boolean",
			SpecialType.System_Byte or SpecialType.System_SByte or
				SpecialType.System_Int16 or SpecialType.System_UInt16 or
				SpecialType.System_Int32 or SpecialType.System_UInt32 or
				SpecialType.System_Int64 or SpecialType.System_UInt64 or
				SpecialType.System_Single or SpecialType.System_Double or
				SpecialType.System_Decimal => "number",
			SpecialType.System_Object => "unknown",
			_ when type.TypeKind == TypeKind.Enum => type.Name,
			_ when type.ToDisplayString() is "System.Guid" or "System.DateTime" or "System.DateTimeOffset" or
				"System.DateOnly" or "System.TimeOnly" or "System.TimeSpan" or "System.Uri" => "string",
			_ => null
		};

	private static bool IsSimple(INamedTypeSymbol type) =>
		SimpleType(type) is not null || type.ToDisplayString() == "System.Threading.CancellationToken";

	private static bool TryCollection(INamedTypeSymbol type, out ITypeSymbol element)
	{
		var candidate = type.AllInterfaces.Append(type)
			.FirstOrDefault(t => t.IsGenericType && t.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.IEnumerable<T>");
		element = candidate?.TypeArguments[0]!;
		return candidate is not null && !TryDictionary(type, out _, out _);
	}

	private static bool IsCollection(INamedTypeSymbol type) => TryCollection(type, out _);

	private static bool TryDictionary(INamedTypeSymbol type, out ITypeSymbol key, out ITypeSymbol value)
	{
		var candidate = type.AllInterfaces.Append(type)
			.FirstOrDefault(t => t.IsGenericType && t.OriginalDefinition.ToDisplayString() == "System.Collections.Generic.IDictionary<TKey, TValue>");
		key = candidate?.TypeArguments[0]!;
		value = candidate?.TypeArguments[1]!;
		return candidate is not null;
	}

	private static bool IsDictionary(INamedTypeSymbol type) => TryDictionary(type, out _, out _);

	private static string DictionaryKeyType(ITypeSymbol key) =>
		key.SpecialType is SpecialType.System_Byte or SpecialType.System_SByte or
			SpecialType.System_Int16 or SpecialType.System_UInt16 or
			SpecialType.System_Int32 or SpecialType.System_UInt32 or
			SpecialType.System_Int64 or SpecialType.System_UInt64 ? "number" : "string";

	private static void CollectImports(ITypeSymbol type, HashSet<string> imports)
	{
		type = StripNullable(type);
		if (type is IArrayTypeSymbol array)
		{
			CollectImports(array.ElementType, imports);
			return;
		}
		if (type is not INamedTypeSymbol named) return;
		foreach (var argument in named.TypeArguments) CollectImports(argument, imports);
		if (!IsSimple(named) && !IsCollection(named) && !IsDictionary(named) && named.SpecialType == SpecialType.None)
			imports.Add(named.Name);
	}

	private static ITypeSymbol StripNullable(ITypeSymbol type) =>
		type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } nullable
			? nullable.TypeArguments[0]
			: type;

	internal static bool IsNullable(ITypeSymbol type, NullableAnnotation annotation) =>
		type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Nullable_T } ||
		annotation == NullableAnnotation.Annotated;

	private static bool IsCancellationToken(ITypeSymbol type) =>
		type.ToDisplayString() == "System.Threading.CancellationToken";

	private static string FullType(ITypeSymbol type) =>
		type.WithNullableAnnotation(NullableAnnotation.None).ToDisplayString(FullTypeFormat);

	private static string TypeOf(INamedTypeSymbol type)
	{
		var prefix = type.ContainingType is null
			? type.ContainingNamespace.IsGlobalNamespace ? "global::" : $"global::{type.ContainingNamespace.ToDisplayString()}."
			: TypeOfContaining(type.ContainingType) + ".";
		return type.Arity == 0 ? prefix + type.Name : prefix + type.Name + "<" + new string(',', type.Arity - 1) + ">";
	}

	private static string TypeOfContaining(INamedTypeSymbol type)
	{
		var prefix = type.ContainingType is null
			? type.ContainingNamespace.IsGlobalNamespace ? "global::" : $"global::{type.ContainingNamespace.ToDisplayString()}."
			: TypeOfContaining(type.ContainingType) + ".";
		return type.Arity == 0 ? prefix + type.Name : prefix + type.Name + "<" + new string(',', type.Arity - 1) + ">";
	}

	private static string TypeScriptName(INamedTypeSymbol type) =>
		type.Arity == 0 ? type.Name : $"{type.Name}<{string.Join(", ", type.TypeParameters.Select(p => p.Name))}>";

	private static string JsonName(IPropertySymbol property)
	{
		var attribute = Attribute(property, "System.Text.Json.Serialization.JsonPropertyNameAttribute");
		return attribute?.ConstructorArguments.FirstOrDefault().Value as string ?? CamelCase(property.Name);
	}

	private static bool IsIgnored(IPropertySymbol property)
	{
		var attribute = Attribute(property, "System.Text.Json.Serialization.JsonIgnoreAttribute");
		if (attribute is null) return false;
		var condition = attribute.NamedArguments.FirstOrDefault(a => a.Key == "Condition").Value.Value;
		return condition is null || Convert.ToInt32(condition) == 1;
	}

	private static bool IsConditionallyIgnored(IPropertySymbol property)
	{
		var attribute = Attribute(property, "System.Text.Json.Serialization.JsonIgnoreAttribute");
		var condition = attribute?.NamedArguments.FirstOrDefault(a => a.Key == "Condition").Value.Value;
		return condition is not null && Convert.ToInt32(condition) is 2 or 3;
	}

	private static bool HasJsonConverter(ISymbol symbol) =>
		Attribute(symbol, "System.Text.Json.Serialization.JsonConverterAttribute") is not null;

	private static AttributeData? Attribute(ISymbol symbol, string fullName) =>
		symbol.GetAttributes().FirstOrDefault(a => a.AttributeClass?.ToDisplayString() == fullName);

	private static string PageComponent(INamedTypeSymbol page)
	{
		var componentAttribute = Attribute(page, "SvelteNet.SvelteComponentAttribute");
		if (componentAttribute?.ConstructorArguments.FirstOrDefault().Value is string component)
			return component;

		var name = page.Name.EndsWith("Model", StringComparison.Ordinal) && page.Name.Length > 5
			? page.Name.Substring(0, page.Name.Length - 5)
			: page.Name;
		var ns = page.ContainingNamespace.ToDisplayString();
		var marker = ns.IndexOf(".Pages", StringComparison.Ordinal);
		if (marker < 0) return name;
		var directory = ns.Substring(marker + ".Pages".Length).Trim('.').Replace('.', '/');
		return directory.Length == 0 ? name : $"{directory}/{name}";
	}

	private static string TrimModelSuffix(string name)
	{
		foreach (var suffix in new[] { "ViewModel", "Model", "Dto" })
		{
			if (name.Length > suffix.Length && name.EndsWith(suffix, StringComparison.Ordinal))
				return name.Substring(0, name.Length - suffix.Length);
		}
		return name;
	}

	private static string CamelCase(string name)
	{
		if (string.IsNullOrEmpty(name) || !char.IsUpper(name[0])) return name;
		var chars = name.ToCharArray();
		for (var i = 0; i < chars.Length; i++)
		{
			if (i > 0 && i + 1 < chars.Length && !char.IsUpper(chars[i + 1])) break;
			chars[i] = char.ToLowerInvariant(chars[i]);
		}
		return new string(chars);
	}

	private static string EscapeIdentifier(string name) =>
		SyntaxFacts.GetKeywordKind(name) == SyntaxKind.None ? name : "@" + name;

	private static string TypeScriptPropertyName(string name) =>
		name.Length > 0 && (char.IsLetter(name[0]) || name[0] is '_' or '$') &&
		name.Skip(1).All(c => char.IsLetterOrDigit(c) || c is '_' or '$')
			? name
			: $"\"{EscapeTypeScriptString(name)}\"";

	private static string EscapeTypeScriptString(string value) =>
		value.Replace("\\", "\\\\").Replace("'", "\\'").Replace("\"", "\\\"");

	private static string Literal(string value) =>
		"\"" + value
			.Replace("\\", "\\\\")
			.Replace("\"", "\\\"")
			.Replace("\r", "\\r")
			.Replace("\n", "\\n") + "\"";

	private static uint StableHash(string value)
	{
		const uint offset = 2166136261;
		const uint prime = 16777619;
		var hash = offset;
		foreach (var c in value)
		{
			hash ^= c;
			hash *= prime;
		}
		return hash;
	}
}
