/* eslint-disable */
// Generated by SvelteNet — do not edit.
import { command, query } from 'sveltenet/remote';

export class WeatherApi {
	static readonly GetForecasts = query<WeatherForecast[]>('WeatherApi/GetForecasts');
	static readonly RefreshForecasts = command<string>('WeatherApi/RefreshForecasts');
}
